"""
nginx_writer.py — Generates the nginx cookie-based upstream map file and
triggers a safe nginx reload.

Map file format (written to NGINX_MAP_PATH):
--------------------------------------------
map $cookie_dlsess $honeytrap_upstream {
    default                     "level1_pool";
    "dlsess_<session_hash>"     "host:port";
    ...
}

The map is atomically replaced (write to .tmp then rename) to avoid nginx
reading a partially written file.
"""

from __future__ import annotations

import logging
import os
import subprocess
import tempfile
from typing import Dict, Optional

logger = logging.getLogger(__name__)

NGINX_MAP_PATH: str = os.environ.get("NGINX_MAP_PATH", "/etc/nginx/conf.d/dl_upstream_map.conf")
NGINX_PID_PATH: str = os.environ.get("NGINX_PID_PATH", "/var/run/nginx.pid")
LEVEL1_POOL: str = os.environ.get("LEVEL1_POOL_UPSTREAM", "level1_pool")


# ---------------------------------------------------------------------------
# Map generation
# ---------------------------------------------------------------------------

def _build_map(session_upstreams: Dict[str, str]) -> str:
    """
    Build the nginx map block string.

    Args:
        session_upstreams: {cookie_value: "host:port"}
    """
    lines = [
        "# Auto-generated by dynamic-labyrinth orchestrator — DO NOT EDIT MANUALLY",
        f'map $cookie_dlsess $honeytrap_upstream {{',
        f'    default    "{LEVEL1_POOL}";',
    ]
    for cookie_val, upstream in sorted(session_upstreams.items()):
        # Sanitise: allow only safe characters in cookie values and upstreams
        safe_cookie = _sanitise(cookie_val, max_len=128)
        safe_upstream = _sanitise(upstream, max_len=128)
        if safe_cookie and safe_upstream:
            lines.append(f'    "{safe_cookie}"    "{safe_upstream}";')
    lines.append("}")
    return "\n".join(lines) + "\n"


def _sanitise(value: str, max_len: int = 128) -> str:
    """Strip characters unsafe in nginx config values."""
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789._:-")
    clean = "".join(c for c in value if c in allowed)
    return clean[:max_len]


# ---------------------------------------------------------------------------
# Atomic file write
# ---------------------------------------------------------------------------

def write_map_file(session_upstreams: Dict[str, str]) -> None:
    """
    Atomically write the nginx map file.
    Uses write-to-tmp + os.replace to prevent partial reads by nginx.
    """
    content = _build_map(session_upstreams)
    map_dir = os.path.dirname(NGINX_MAP_PATH)
    if map_dir:
        os.makedirs(map_dir, exist_ok=True)

    tmp_fd, tmp_path = tempfile.mkstemp(dir=map_dir or ".", prefix=".dl_map_")
    try:
        with os.fdopen(tmp_fd, "w") as fh:
            fh.write(content)
        os.replace(tmp_path, NGINX_MAP_PATH)
        logger.info("Nginx map written: %d entries → %s", len(session_upstreams), NGINX_MAP_PATH)
    except Exception as exc:
        logger.error("Failed to write nginx map: %s", exc)
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


# ---------------------------------------------------------------------------
# Nginx reload
# ---------------------------------------------------------------------------

def _nginx_alive() -> bool:
    """Return True if nginx is running (PID file exists and process is alive)."""
    try:
        with open(NGINX_PID_PATH) as fh:
            pid = int(fh.read().strip())
        os.kill(pid, 0)  # signal 0 = check existence
        return True
    except (OSError, ValueError):
        return False


def reload_nginx() -> bool:
    """
    Send a graceful reload signal to nginx after validating the config.
    Returns True on success.
    """
    if not _nginx_alive():
        logger.warning("nginx does not appear to be running — skipping reload")
        return False

    # Test config first to avoid reloading a broken file
    test_result = subprocess.run(
        ["nginx", "-t"],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if test_result.returncode != 0:
        logger.error("nginx -t failed:\n%s", test_result.stderr)
        return False

    reload_result = subprocess.run(
        ["nginx", "-s", "reload"],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if reload_result.returncode != 0:
        logger.error("nginx reload failed:\n%s", reload_result.stderr)
        return False

    logger.info("nginx reloaded successfully")
    return True


# ---------------------------------------------------------------------------
# Combined helper: write + reload
# ---------------------------------------------------------------------------

def update_nginx(session_upstreams: Dict[str, str]) -> bool:
    """Write the map file and trigger a reload. Returns True on full success."""
    write_map_file(session_upstreams)
    return reload_nginx()


# ---------------------------------------------------------------------------
# Active session upstream loader
# ---------------------------------------------------------------------------

def load_active_upstreams() -> Dict[str, str]:
    """
    Read all active (non-released) session→container mappings from the DB
    and return {cookie_value: upstream} for map generation.
    """
    from pool_manager import _get_conn

    conn = _get_conn()
    try:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT s.session_id, c.host, c.port
            FROM sessions s
            JOIN containers c ON s.container_id = c.id
            WHERE s.released = 0
            """
        )
        rows = cur.fetchall()
    finally:
        conn.close()

    upstreams: Dict[str, str] = {}
    for row in rows:
        cookie = f"dlsess_{row['session_id']}"
        upstream = f"{row['host']}:{row['port']}"
        upstreams[cookie] = upstream
    return upstreams


def rebuild_nginx_map() -> bool:
    """Rebuild the full nginx map from current DB state and reload."""
    upstreams = load_active_upstreams()
    return update_nginx(upstreams)
